#!/usr/bin/env python3

import yaml
from argparse import ArgumentParser
from config import add_default_config_args, init_config_parser, handle_config_command, Config
from data import init_data_parser, handle_data_command
from pathlib import Path

def main():
    parser = ArgumentParser()
    add_default_config_args(parser)

    parsers = parser.add_subparsers(dest="command")
    config_parser = parsers.add_parser("config", help="Reads and writes the global config data")
    init_config_parser(config_parser)
    
    data_parser = parsers.add_parser("data", help="Manages static game data (realms, professions, items)")
    init_data_parser(data_parser)

    args = parser.parse_args()

    config = Config()
    config.load()
    config.update_from_args(args)

    if args.command == "config":
        exit(handle_config_command(args, config))
    
    if not config.validate:
        print("Invalid config, call hogo config init first")
        exit(1)
    
    if args.command == "data":
        handle_data_command(args, config)


if __name__=="__main__":
    main()